name: CI

on:
  push:
    branches: [ main , dev ]
  pull_request:
    branches: [ main , dev ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.5.1
        with:
          node-version: '16.14.0'
          
      - name: Install Yarn
        run: npm install -g yarn
        
      - name: Run yarn install
        run: yarn install


      # Runs a set of commands using the runners shell
      - name: Run yarn check eslint
        run: |
          yarn tsc
          yarn run eslint .
